# name: Go CI/CD Pipline

# on:
#     push: 
#         branches: 
#             - main

# jobs:
#     first-job:
#         name: Build and test
#         runs-on: ubuntu-latest

#         steps:
#             - name: Checkout code
#               uses: actions/checkout@v3
            
#             - name: Set up Golang
#               uses: actions/setup-go@v4
#               with:
#                 go-version: 1.21 # golang version
            
#             - name: Build and test
#               run: |
#                 go build
#                 go test 

name: Print Hello World

on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: Print HelloWorld
              run: echo "Hello World"
