name: Go CI/CD Pipline

on:
    push: 
        branches: 
            - main

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Golang
              uses: actions/setup-go@v4
              with:
                go-version: 1.21 # golang version
            
            - name: Build and test
              run: |
                go build
                go test
        
    hello_world:
        name: Print HelloWorld
        runs-on: ubuntu-latest

        steps:
          - name: Print HelloWorld Statement
            run: |
              echo "Hello World"
